/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.trabalho_01_bimestre.view;

import com.mycompany.trabalho_01_bimestre.model.Cliente;
import com.mycompany.trabalho_01_bimestre.model.OrdemServico;
import com.mycompany.trabalho_01_bimestre.model.Servicos;
import com.mycompany.trabalho_01_bimestre.model.Veiculo;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author joaoc
 */
public class TelaInicialFrame extends javax.swing.JFrame {
    Integer countVeiculo = 0;
    Integer countCliente = 0;
    Integer countOs = 0;
    ArrayList listaVeiculo = new ArrayList<Veiculo>();
    ArrayList listaOS = new ArrayList<OrdemServico>();
    ArrayList listaServiços = new ArrayList<>();
    Integer vlTotal = 0;
    Integer vl1 = 0;
    Integer vl2 = 0;
    Integer vl3 = 0;
    Integer vl4 = 0;
    Integer vl5 = 0;
    Integer vl6 = 0;
    Integer vl7 = 0;
    Integer vl8 = 0;
    Integer vl9 = 0;
    Integer vl10 = 0;
     private DefaultTableModel tbModelo = new DefaultTableModel();
     private int linhaSelecionada = -1;
    /**
     * Creates new form TelaInicialFrame
     */
    public TelaInicialFrame() {
        initComponents();
        carregaTabela();
        countOs += 1;
    }
    
    public void carregaTabela(){
        tbModelo.addColumn("Codigo");
        tbModelo.addColumn("Placa");
        tbModelo.addColumn("Marca");
        tbModelo.addColumn("Modelo");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        ExtratoOS = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tfNomeCliente = new javax.swing.JTextField();
        tfTelefoneCliente = new javax.swing.JTextField();
        tfEnderecoCliente = new javax.swing.JTextField();
        btSalvarCliente = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        tfPlaca = new javax.swing.JTextField();
        tfMarca = new javax.swing.JTextField();
        tfModelo = new javax.swing.JTextField();
        tfAno = new javax.swing.JTextField();
        tfCor = new javax.swing.JTextField();
        btSalvarVeiculo = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        tfDescricao = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tfClienteNome = new javax.swing.JTextField();
        tfTelefone = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        tfEndereco = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        tfPlacaOs = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jCbBalanceamento = new javax.swing.JCheckBox();
        jCbAlinhamento = new javax.swing.JCheckBox();
        jCbTrocarVela = new javax.swing.JCheckBox();
        jCbTrocaPneus = new javax.swing.JCheckBox();
        jCbTrocaOleo = new javax.swing.JCheckBox();
        jCbTrocaBomba = new javax.swing.JCheckBox();
        jCbTrocaFiltroAr = new javax.swing.JCheckBox();
        jCbTrocaFluido = new javax.swing.JCheckBox();
        jCbTrocaAgua = new javax.swing.JCheckBox();
        jCbCalibrarPneu = new javax.swing.JCheckBox();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        tfTotal = new javax.swing.JTextField();
        btSalvarOS = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        tfDescricaoEOS = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        tfNomeEOS = new javax.swing.JTextField();
        tfTelefoneEOS = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        tfEnderecoEOS = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        tfPlacaEOS = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jCbBalanceamento1 = new javax.swing.JCheckBox();
        jCbAlinhamento1 = new javax.swing.JCheckBox();
        jCbTrocarVela1 = new javax.swing.JCheckBox();
        jCbTrocaPneus1 = new javax.swing.JCheckBox();
        jCbTrocaOleo1 = new javax.swing.JCheckBox();
        jCbTrocaBomba1 = new javax.swing.JCheckBox();
        jCbTrocaFiltroAr1 = new javax.swing.JCheckBox();
        jCbTrocaFluido1 = new javax.swing.JCheckBox();
        jCbTrocaAgua1 = new javax.swing.JCheckBox();
        jCbCalibrarPneu1 = new javax.swing.JCheckBox();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        tfTotalEOS = new javax.swing.JTextField();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        jLabel2.setText("Dados do Cliente");

        jLabel1.setText("Nome");

        jLabel3.setText("Telefone");

        jLabel4.setText("Endereço");

        tfNomeCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNomeClienteActionPerformed(evt);
            }
        });

        btSalvarCliente.setText("Salvar Cliente");
        btSalvarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarClienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel1))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(142, 142, 142)
                            .addComponent(jLabel2))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel4)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tfEnderecoCliente, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfNomeCliente, javax.swing.GroupLayout.Alignment.LEADING))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 286, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel3)
                        .addComponent(tfTelefoneCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btSalvarCliente, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfTelefoneCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfEnderecoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btSalvarCliente))
                .addGap(210, 210, 210))
        );

        ExtratoOS.addTab("Cadastro de Cliente", jPanel1);

        jLabel6.setText("Cadastro de Veiculo");

        jLabel7.setText("Placa");

        jLabel8.setText("Marca");

        jLabel9.setText("Modelo");

        jLabel10.setText("Cor");

        jLabel11.setText("Ano");

        tfModelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfModeloActionPerformed(evt);
            }
        });

        btSalvarVeiculo.setText("Salvar Veículo");
        btSalvarVeiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarVeiculoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(173, 173, 173))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel11))
                                .addGap(178, 178, 178)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel10)
                            .addComponent(jLabel9)
                            .addComponent(tfModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfCor, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(tfPlaca)
                        .addComponent(tfMarca, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                        .addComponent(tfAno))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(109, 109, 109)))
                .addGap(38, 302, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btSalvarVeiculo)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel6)
                .addGap(12, 12, 12)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfCor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 218, Short.MAX_VALUE)
                .addComponent(btSalvarVeiculo)
                .addContainerGap())
        );

        ExtratoOS.addTab("Cadastro de Veiculo", jPanel2);

        jLabel12.setText("Ordem de Serviço(OS)");

        tfDescricao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfDescricaoActionPerformed(evt);
            }
        });

        jLabel5.setText("Nome");

        tfClienteNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfClienteNomeActionPerformed(evt);
            }
        });

        jLabel13.setText("Telefone");

        jLabel14.setText("Endereço");

        jLabel15.setText("Placa");

        jLabel16.setText("Descrição");

        jCbBalanceamento.setText("Balanceamento");
        jCbBalanceamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCbBalanceamentoActionPerformed(evt);
            }
        });

        jCbAlinhamento.setText("Alinhamento");
        jCbAlinhamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCbAlinhamentoActionPerformed(evt);
            }
        });

        jCbTrocarVela.setText("Trocar vela");
        jCbTrocarVela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCbTrocarVelaActionPerformed(evt);
            }
        });

        jCbTrocaPneus.setText("Troca de pneus");
        jCbTrocaPneus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCbTrocaPneusActionPerformed(evt);
            }
        });

        jCbTrocaOleo.setText("Troca de óleo");
        jCbTrocaOleo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCbTrocaOleoActionPerformed(evt);
            }
        });

        jCbTrocaBomba.setText("Troca de bomba");
        jCbTrocaBomba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCbTrocaBombaActionPerformed(evt);
            }
        });

        jCbTrocaFiltroAr.setText("Troca de filtro de Ar");
        jCbTrocaFiltroAr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCbTrocaFiltroArActionPerformed(evt);
            }
        });

        jCbTrocaFluido.setText("Troca de fluído");
        jCbTrocaFluido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCbTrocaFluidoActionPerformed(evt);
            }
        });

        jCbTrocaAgua.setText("Troca de água");
        jCbTrocaAgua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCbTrocaAguaActionPerformed(evt);
            }
        });

        jCbCalibrarPneu.setText("Calibrar pneu");
        jCbCalibrarPneu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCbCalibrarPneuActionPerformed(evt);
            }
        });

        jLabel18.setText("Serviços");

        jLabel19.setText("Total");

        tfTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfTotalActionPerformed(evt);
            }
        });

        btSalvarOS.setText("Salvar");
        btSalvarOS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarOSActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(268, 268, 268)
                .addComponent(jLabel12)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfDescricao)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfClienteNome, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCbTrocaOleo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jCbTrocaFiltroAr)
                                    .addComponent(jCbTrocaBomba)
                                    .addComponent(jCbTrocaAgua)
                                    .addComponent(jCbTrocaFluido)
                                    .addComponent(jCbCalibrarPneu))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(tfTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfEndereco))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfPlacaOs, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(229, 229, 229)
                                .addComponent(jLabel13)
                                .addGap(106, 106, 106)
                                .addComponent(jLabel14))
                            .addComponent(jLabel15))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCbBalanceamento)
                            .addComponent(jCbAlinhamento)
                            .addComponent(jCbTrocarVela)
                            .addComponent(jCbTrocaPneus)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel16)
                                    .addComponent(tfTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel18)
                                    .addComponent(jLabel19))))
                        .addGap(547, 547, 547))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btSalvarOS)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfClienteNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfPlacaOs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jCbAlinhamento)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCbBalanceamento)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCbTrocaPneus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCbTrocarVela)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCbTrocaOleo))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jCbTrocaBomba)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCbTrocaFiltroAr)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCbTrocaFluido)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCbTrocaAgua)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCbCalibrarPneu)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(btSalvarOS)
                .addContainerGap())
        );

        ExtratoOS.addTab("Ordem de Serviço(s)", jPanel3);

        jLabel17.setText("Ordem de Serviço(OS)");

        tfDescricaoEOS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfDescricaoEOSActionPerformed(evt);
            }
        });

        jLabel20.setText("Nome");

        tfNomeEOS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNomeEOSActionPerformed(evt);
            }
        });

        jLabel21.setText("Telefone");

        jLabel22.setText("Endereço");

        jLabel23.setText("Placa");

        jLabel24.setText("Descrição");

        jCbBalanceamento1.setText("Balanceamento");
        jCbBalanceamento1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCbBalanceamento1ActionPerformed(evt);
            }
        });

        jCbAlinhamento1.setText("Alinhamento");
        jCbAlinhamento1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCbAlinhamento1ActionPerformed(evt);
            }
        });

        jCbTrocarVela1.setText("Trocar vela");
        jCbTrocarVela1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCbTrocarVela1ActionPerformed(evt);
            }
        });

        jCbTrocaPneus1.setText("Troca de pneus");
        jCbTrocaPneus1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCbTrocaPneus1ActionPerformed(evt);
            }
        });

        jCbTrocaOleo1.setText("Troca de óleo");
        jCbTrocaOleo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCbTrocaOleo1ActionPerformed(evt);
            }
        });

        jCbTrocaBomba1.setText("Troca de bomba");
        jCbTrocaBomba1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCbTrocaBomba1ActionPerformed(evt);
            }
        });

        jCbTrocaFiltroAr1.setText("Troca de filtro de Ar");
        jCbTrocaFiltroAr1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCbTrocaFiltroAr1ActionPerformed(evt);
            }
        });

        jCbTrocaFluido1.setText("Troca de fluído");
        jCbTrocaFluido1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCbTrocaFluido1ActionPerformed(evt);
            }
        });

        jCbTrocaAgua1.setText("Troca de água");
        jCbTrocaAgua1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCbTrocaAgua1ActionPerformed(evt);
            }
        });

        jCbCalibrarPneu1.setText("Calibrar pneu");
        jCbCalibrarPneu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCbCalibrarPneu1ActionPerformed(evt);
            }
        });

        jLabel25.setText("Serviços");

        jLabel26.setText("Total");

        tfTotalEOS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfTotalEOSActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(268, 268, 268)
                .addComponent(jLabel17)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfPlacaEOS, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel20)
                                .addGap(229, 229, 229)
                                .addComponent(jLabel21)
                                .addGap(106, 106, 106)
                                .addComponent(jLabel22))
                            .addComponent(jLabel23))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCbBalanceamento1)
                            .addComponent(jCbAlinhamento1)
                            .addComponent(jCbTrocarVela1)
                            .addComponent(jCbTrocaPneus1)
                            .addComponent(jLabel24)
                            .addComponent(tfTotalEOS, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel25)
                            .addComponent(jLabel26))
                        .addGap(553, 553, 553))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfDescricaoEOS)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfNomeEOS, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jCbTrocaOleo1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jCbTrocaFiltroAr1)
                                            .addComponent(jCbTrocaBomba1)
                                            .addComponent(jCbTrocaAgua1)
                                            .addComponent(jCbTrocaFluido1)
                                            .addComponent(jCbCalibrarPneu1))
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addComponent(tfTelefoneEOS, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tfEnderecoEOS)))))
                        .addContainerGap())))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel24)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfDescricaoEOS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(jLabel21)
                    .addComponent(jLabel22))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfNomeEOS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfTelefoneEOS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfEnderecoEOS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel23)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfPlacaEOS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(jLabel25)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jCbAlinhamento1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCbBalanceamento1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCbTrocaPneus1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCbTrocarVela1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCbTrocaOleo1))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jCbTrocaBomba1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCbTrocaFiltroAr1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCbTrocaFluido1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCbTrocaAgua1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCbCalibrarPneu1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel26)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfTotalEOS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(68, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 664, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 457, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        ExtratoOS.addTab("Extrato OS", jPanel4);

        getContentPane().add(ExtratoOS);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfModeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfModeloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfModeloActionPerformed

    private void btSalvarVeiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarVeiculoActionPerformed
        Veiculo veiculo = new Veiculo();
        
        veiculo.setIdVeiculo(countVeiculo += 1);
        veiculo.setPlaca(tfPlaca.getText());
        veiculo.setMarca(tfMarca.getText());
        veiculo.setModelo(tfModelo.getText());
        veiculo.setAno(tfAno.getText());
        veiculo.setCor(tfCor.getText());
        
        listaVeiculo.add(veiculo);
        
        Integer codigo = veiculo.getIdVeiculo();
        String placa = veiculo.getPlaca();
        String marca = veiculo.getMarca();
        String modelo = veiculo.getModelo();
        
        tbModelo.addRow(new Object[]{codigo, placa, marca, modelo});
        
    }//GEN-LAST:event_btSalvarVeiculoActionPerformed

    private void btSalvarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarClienteActionPerformed
        try{
            Cliente cliente = new Cliente();
            cliente.setId(countCliente += 1);
            cliente.setNome(tfNomeCliente.getText());
            cliente.setEndereco(tfEnderecoCliente.getText());
            cliente.setTelefone(tfTelefoneCliente.getText());
        }catch(Exception ex){
            JOptionPane.showMessageDialog(this, "Nao foi possivel inserir o veículo.");
        }

    }//GEN-LAST:event_btSalvarClienteActionPerformed

    private void tfNomeClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNomeClienteActionPerformed

    }//GEN-LAST:event_tfNomeClienteActionPerformed

    private void tfClienteNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfClienteNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfClienteNomeActionPerformed

    private void tfDescricaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfDescricaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfDescricaoActionPerformed

    private void jCbAlinhamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCbAlinhamentoActionPerformed
        if(jCbAlinhamento.isSelected() && vl1 == 0){
            vlTotal += 50;
            vl1 += 50;
        }else{
            vl1 -= 50;
            vlTotal -= 50;
        }
        tfTotal.setText(Double.toString(vlTotal));
    }//GEN-LAST:event_jCbAlinhamentoActionPerformed

    private void tfTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfTotalActionPerformed
       
    }//GEN-LAST:event_tfTotalActionPerformed

    private void jCbBalanceamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCbBalanceamentoActionPerformed
        if(jCbBalanceamento.isSelected() && vl2 == 0){
            vlTotal += 60;
            vl2 += 60;
        }else{
            vl2 -= 60;
            vlTotal -= 60;
        }
        tfTotal.setText(Double.toString(vlTotal));
    
    }//GEN-LAST:event_jCbBalanceamentoActionPerformed

    private void jCbTrocaPneusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCbTrocaPneusActionPerformed
       if(jCbTrocaPneus.isSelected() && vl3 == 0){
            vlTotal += 150;
            vl3 += 150;
        }else{
            vl3 -= 150;
            vlTotal -= 150;
        }
        tfTotal.setText(Double.toString(vlTotal));
    }//GEN-LAST:event_jCbTrocaPneusActionPerformed

    private void jCbTrocarVelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCbTrocarVelaActionPerformed
        if(jCbTrocarVela.isSelected() && vl4 == 0){
            vlTotal += 180;
            vl4 += 180;
        }else{
            vl4 -= 180;
            vlTotal -= 180;
        }
        tfTotal.setText(Double.toString(vlTotal));
         
    }//GEN-LAST:event_jCbTrocarVelaActionPerformed

    private void jCbTrocaOleoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCbTrocaOleoActionPerformed
        if(jCbTrocaOleo.isSelected() && vl5 == 0){
            vlTotal += 300;
            vl5 += 300;
        }else{
            vl5 -= 300;
            vlTotal -= 300;
        }
        tfTotal.setText(Double.toString(vlTotal));
    }//GEN-LAST:event_jCbTrocaOleoActionPerformed

    private void jCbTrocaBombaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCbTrocaBombaActionPerformed
        if(jCbTrocaBomba.isSelected() && vl6 == 0){
            vlTotal += 550;
            vl6 += 550;
        }else{
            vl6 -= 550;
            vlTotal -= 550;
        }
        tfTotal.setText(Double.toString(vlTotal));
    }//GEN-LAST:event_jCbTrocaBombaActionPerformed

    private void jCbTrocaFiltroArActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCbTrocaFiltroArActionPerformed
        if(jCbTrocaFiltroAr.isSelected() && vl7 == 0){
            vlTotal += 340;
            vl7 += 340;
        }else{
            vl7 -= 340;
            vlTotal -= 340;
        }
        tfTotal.setText(Double.toString(vlTotal));
    }//GEN-LAST:event_jCbTrocaFiltroArActionPerformed

    private void jCbTrocaFluidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCbTrocaFluidoActionPerformed
        if(jCbTrocaFluido.isSelected() && vl8 == 0){
            vlTotal += 65;
            vl8 += 65;
        }else{
            vl8 -= 65;
            vlTotal -= 65;
        }
        tfTotal.setText(Double.toString(vlTotal));
    }//GEN-LAST:event_jCbTrocaFluidoActionPerformed

    private void jCbTrocaAguaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCbTrocaAguaActionPerformed
        if(jCbTrocaAgua.isSelected() && vl9 == 0){
            vlTotal += 20;
            vl9 += 20;
        }else{
            vl9 -= 20;
            vlTotal -= 20;
        }
        tfTotal.setText(Double.toString(vlTotal));
    }//GEN-LAST:event_jCbTrocaAguaActionPerformed

    private void jCbCalibrarPneuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCbCalibrarPneuActionPerformed
        if(jCbCalibrarPneu.isSelected() && vl10 == 0){
            vlTotal += 10;
            vl10 += 10;
        }else{
            vl10 -= 10;
            vlTotal -= 10;
        }
        tfTotal.setText(Double.toString(vlTotal));
    }//GEN-LAST:event_jCbCalibrarPneuActionPerformed

    private void btSalvarOSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarOSActionPerformed
        OrdemServico os = new OrdemServico();
        os.setDescricao(tfDescricao.getText());
        os.setEndereco(tfEndereco.getText());
        os.setNomeCliente(tfNomeCliente.getText());
        os.setPlaca(tfPlaca.getText());
        os.setTelefone(tfTelefone.getText());
        os.setTotal(Integer.parseInt(tfTotal.getText()));
        
        listaOS.add(os);
        new TelaInicialFrame().ExtratoOS.setVisible(true);
        OrdemServico extrato = new OrdemServico();
        extrato.setDescricao(tfDescricaoEOS.getText());
        extrato.setEndereco(tfEnderecoEOS.getText());
        extrato.setNomeCliente(tfNomeEOS.getText());
        extrato.setPlaca(tfPlacaEOS.getText());
        extrato.setTelefone(tfTelefoneEOS.getText());
        extrato.setTotal(Integer.parseInt(tfTotalEOS.getText()));
        
        
    }//GEN-LAST:event_btSalvarOSActionPerformed

    private void tfDescricaoEOSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfDescricaoEOSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfDescricaoEOSActionPerformed

    private void tfNomeEOSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNomeEOSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNomeEOSActionPerformed

    private void jCbBalanceamento1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCbBalanceamento1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCbBalanceamento1ActionPerformed

    private void jCbAlinhamento1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCbAlinhamento1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCbAlinhamento1ActionPerformed

    private void jCbTrocarVela1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCbTrocarVela1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCbTrocarVela1ActionPerformed

    private void jCbTrocaPneus1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCbTrocaPneus1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCbTrocaPneus1ActionPerformed

    private void jCbTrocaOleo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCbTrocaOleo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCbTrocaOleo1ActionPerformed

    private void jCbTrocaBomba1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCbTrocaBomba1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCbTrocaBomba1ActionPerformed

    private void jCbTrocaFiltroAr1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCbTrocaFiltroAr1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCbTrocaFiltroAr1ActionPerformed

    private void jCbTrocaFluido1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCbTrocaFluido1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCbTrocaFluido1ActionPerformed

    private void jCbTrocaAgua1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCbTrocaAgua1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCbTrocaAgua1ActionPerformed

    private void jCbCalibrarPneu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCbCalibrarPneu1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCbCalibrarPneu1ActionPerformed

    private void tfTotalEOSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfTotalEOSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfTotalEOSActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane ExtratoOS;
    private javax.swing.JButton btSalvarCliente;
    private javax.swing.JButton btSalvarOS;
    private javax.swing.JButton btSalvarVeiculo;
    private javax.swing.JCheckBox jCbAlinhamento;
    private javax.swing.JCheckBox jCbAlinhamento1;
    private javax.swing.JCheckBox jCbBalanceamento;
    private javax.swing.JCheckBox jCbBalanceamento1;
    private javax.swing.JCheckBox jCbCalibrarPneu;
    private javax.swing.JCheckBox jCbCalibrarPneu1;
    private javax.swing.JCheckBox jCbTrocaAgua;
    private javax.swing.JCheckBox jCbTrocaAgua1;
    private javax.swing.JCheckBox jCbTrocaBomba;
    private javax.swing.JCheckBox jCbTrocaBomba1;
    private javax.swing.JCheckBox jCbTrocaFiltroAr;
    private javax.swing.JCheckBox jCbTrocaFiltroAr1;
    private javax.swing.JCheckBox jCbTrocaFluido;
    private javax.swing.JCheckBox jCbTrocaFluido1;
    private javax.swing.JCheckBox jCbTrocaOleo;
    private javax.swing.JCheckBox jCbTrocaOleo1;
    private javax.swing.JCheckBox jCbTrocaPneus;
    private javax.swing.JCheckBox jCbTrocaPneus1;
    private javax.swing.JCheckBox jCbTrocarVela;
    private javax.swing.JCheckBox jCbTrocarVela1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField tfAno;
    private javax.swing.JTextField tfClienteNome;
    private javax.swing.JTextField tfCor;
    private javax.swing.JTextField tfDescricao;
    private javax.swing.JTextField tfDescricaoEOS;
    private javax.swing.JTextField tfEndereco;
    private javax.swing.JTextField tfEnderecoCliente;
    private javax.swing.JTextField tfEnderecoEOS;
    private javax.swing.JTextField tfMarca;
    private javax.swing.JTextField tfModelo;
    private javax.swing.JTextField tfNomeCliente;
    private javax.swing.JTextField tfNomeEOS;
    private javax.swing.JTextField tfPlaca;
    private javax.swing.JTextField tfPlacaEOS;
    private javax.swing.JTextField tfPlacaOs;
    private javax.swing.JTextField tfTelefone;
    private javax.swing.JTextField tfTelefoneCliente;
    private javax.swing.JTextField tfTelefoneEOS;
    private javax.swing.JTextField tfTotal;
    private javax.swing.JTextField tfTotalEOS;
    // End of variables declaration//GEN-END:variables
}
